# -*- coding: utf-8 -*-
"""Yolo_1(v5).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12vaeWwKWqmoaAHuoB9xYxxn-ERR_1hiZ
"""

from google.colab import drive
drive.mount('/content/gdrive')

# make sure you use Tesla K80 GPU (12GB), by changing 'runtmie type' 
!nvidia-smi

!git clone https://github.com/ultralytics/yolov5  # clone repo
!pip install -r yolov5/requirements.txt  # install dependencies

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

from google.colab import files
uploaded = files.upload()

!python detect.py --source P1033673.mp4

from google.colab import files
files.download('/content/yolov5/inference/output/P1033673.mp4')